project_portal_index:
    pattern:  /index
    defaults: { _controller: ProjectPortalBundle:Posts:index }
project_portal_view:
    pattern:  /view/{post_id}
    defaults: { _controller: ProjectPortalBundle:Posts:view }

project_portal_add:
    pattern:  /add
    defaults: { _controller: ProjectPortalBundle:Posts:add }