project_portal_welcome:
    pattern:  /welcome
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    'ProjectPortalBundle:Default:welcome.html.twig'
project_portal_index:
    pattern:  /index
    defaults: { _controller: ProjectPortalBundle:Post:index }
project_portal_view:
    pattern:  /post/{post_id}
    defaults: { _controller: ProjectPortalBundle:Post:view }
project_portal_add:
    pattern:  /add
    defaults: { _controller: ProjectPortalBundle:Post:add }
project_portal_edit:
    pattern:  /post/{post_id}/edit
    defaults: { _controller: ProjectPortalBundle:Post:edit }
project_portal_delete:
    pattern:  /post/{post_id}/delete
    defaults: { _controller: ProjectPortalBundle:Post:delete }
project_portal_comment:
    pattern:  /post/{post_id}/comment
    defaults: { _controller: ProjectPortalBundle:Comment:add }
project_portal_comment_edit:
    pattern:  /comment/{comment_id}/edit
    defaults: { _controller: ProjectPortalBundle:Comment:edit }
project_portal_comment_delete:
    pattern:  /comment/{comment_id}/delete
    defaults: { _controller: ProjectPortalBundle:Comment:delete }
project_portal_users:
    pattern:  /users
    defaults: { _controller: ProjectPortalBundle:User:index }
project_portal_user:
    pattern:  /user/{user_id}
    defaults: { _controller: ProjectPortalBundle:User:view }
project_portal_user_posts:
    pattern:  /user/{user_id}/posts
    defaults: { _controller: ProjectPortalBundle:User:view_posts }
project_portal_tag_view:
    pattern:  /tag/{tag_name}
    defaults: { _controller: ProjectPortalBundle:Tag:view }
project_portal_register:
    pattern:  /register
    defaults: { _controller: ProjectPortalBundle:User:add }
login:
    pattern:   /login
    defaults: { _controller: ProjectPortalBundle:Security:login }
login_check:
    pattern:   /login_check
logout:
    pattern:   /logout