Project\PortalBundle\Entity\Post:
    properties:
        postDate:
            - NotBlank: ~
            - DateTime: ~
        postBody:
            - NotBlank: ~
            - MinLength: {limit: 3}
            - MaxLength: {limit: 2000}			
Project\PortalBundle\Entity\User:
    properties:
        username:
            - NotBlank: ~
            - MinLength: {limit: 3}
            - MaxLength: {limit: 32}
        password:
            - NotBlank: ~
            - MinLength: {limit: 3}
            - MaxLength: {limit: 15}
        email:
            - NotBlank: ~
            - MinLength: {limit: 3}
            - MaxLength: {limit: 20}
            - Regex: "/^([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})$/i"
        gender:
            - NotBlank: ~
            - MinLength: {limit: 1}
            - MaxLength: {limit: 1}
            - Choice:
                choices:  [m, f]
        birthDate:
            - NotBlank: ~
            - DateTime: ~
        city:
            - NotBlank: ~
            - MinLength: {limit: 3}
            - MaxLength: {limit: 20}
        phone:
            - Regex: "\b^[0-9]*$\b"
            - MinLength: {limit: 6}
            - MaxLength: {limit: 12}
        city:
            - NotBlank: ~
            - MinLength: {limit: 6}
            - MaxLength: {limit: 15}
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: username