Project\PortalBundle\Entity\Post:
    properties:
        postDate:
            - NotBlank: ~
            - DateTime: ~
        postBody:
            - NotBlank: ~
            - MinLength: {limit: 3}
            - MaxLength: {limit: 2000}