parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: 10_kuciel
    database_user: 10_kuciel
    database_password: M1n3s9z7
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: sekretnyklucz
    database_path: null
