jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Project\PortalBundle\Entity\User:
            algorithm: md5
            encode_as_base64: false
            iterations:       0

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        administrators:
            entity: { class: ProjectPortalBundle:User, property: username }
        in_memory:
            memory:
                users:
                    admin:
                        password: admin123
                        roles: 'ROLE_ADMIN'

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  /login$
            security: false

        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  login
                check_path:  login_check
            logout:
                path:   logout
                target: login
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
    - { path: ^/welcome$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/register$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/index$, role: ROLE_USER }
    - { path: ^/add$, role: ROLE_USER }
    - { path: ^/logout$, role: ROLE_USER }
    - { path: ^/post/*, role: ROLE_USER }
    - { path: ^/tag/*, role: ROLE_USER }
    - { path: ^/user/*, role: ROLE_USER }
    - { path: ^/message$, role: ROLE_USER }
    - { path: ^/tag/*, role: ROLE_USER }
    - { path: ^/users$, role: ROLE_USER }